# This is the application-local.yml file, used for the local profile.
# This is just an example, we could create multiple profiles like application-dev or application-prod...
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client-contract-api
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080