spring:
  profiles:
      active: local # We are using the local by default, but we could change this to dev, prod...
  datasource:
    # In a real environment, these variables (DB_USER, DB_PASS...) would be defined
    # as environment variables or managed through a secret manager.
    url: jdbc:postgresql://${DB_HOST}:5432/client-contract-api
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080