CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE client (
    id BIGSERIAL PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL
);

CREATE TABLE person_client (
    id BIGSERIAL PRIMARY KEY REFERENCES client(id) ON DELETE CASCADE,
    birthdate DATE NOT NULL
);

CREATE TABLE company_client (
    id BIGSERIAL PRIMARY KEY REFERENCES client(id) ON DELETE CASCADE,
    company_identifier VARCHAR(50) NOT NULL UNIQUE
);
